### ISSUE TITLE
Encoder outputs unparseable leading double quotes

### ISSUE THREAD

**Issue by rick-masters** [gpoore/bespon_py#3]
Some strings with leading double quotes are output unescaped within triple quotes.
This output cannot then be parsed back in. See test program below.

I tried to figure out a solution, but there may be conflicting design points that need to be clarified in order to choose the right solution. On the one hand, the design seems to indicate that double quotes are OK within triple quotes (from your spec):

"Longer delimiter sequences such as ''' and """ may be used to include any unescaped delimiter sequence that is shorter or longer than the delimiters"

One double quote is less than three so that should be legal, unless you meant that there cannot be a longer delimiter sequence *including the leading and trailing delimiters*, in which case that is not at all clear. The conflict is that there appears to be rules in the code that only allow certain numbers of leading double quotes, with four not being one of them. 

While it would be probably be easiest to say that you cannot put unescaped leading quotes in triple quotess, the downside is that too many rules or exceptions in a format are not ideal. An alternative might be a parsing strategy that supports unescaped leading quotes within triple quotes. I have not reasoned through the current strategy as you have, so I cannot say whether there is a good solution there.

By the way, I read your paper on the design of BespON and I was quite impressed with how much thought you have put into its design. The paper was well research, well written, nicely-produced, very informative, and I agree with a great deal of what you had to say. You clearly put a lot of work into that and it deserves more exposure. 

https://conference.scipy.org/proceedings/scipy2017/pdfs/geoffrey_poore.pdf

Besides this glitch, BespON appears to round-trip arbitrary json-like data (like null, empty objects, empty lists, etc) which I think is an essential feature. 

```
import bespon

def test(testobj):
    print(testobj)
    bespon_out = bespon.dumps(testobj)
    print(bespon_out)
    new_obj = bespon.loads(bespon_out)

test('"')    # pass
test('')     # pass
test('{')    # pass
test('}')    # pass
test('}')    # pass
test('"{}"') # fail
test('"}"')  # fail
test('"{"')  # fail
test('{"')   # pass
test('"{')   # fail
test('{"')   # pass
test('}"')   # pass
```

**Comment by gpoore** [comment]
Thanks for the bug report! This should be fixed now on GitHub, and I'll try to put a new release on PyPI soon. Sorry for the delay...too much going at present.

Leading and trailing quotation marks in strings using `"""` delimiters need to be escaped, but leading quotes weren't in these examples. I've updated the test suite as well. I'll still need to revise the relevant part of the spec to clarify this.

**Comment by gpoore** [comment]
The spec is now clarified and a new version is on PyPI, so I'm closing the issue.
